name: Update Postman Workspace

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Sync Postman Collections
      uses: jneate/postman-collection-action@v1
      with:
        postmanApiKey: ${{ secrets.POSTMAN_API_KEY }}
        postmanWorkspaceId: ${{ env.POSTMAN_WORKSPACE_ID }}
