name: Update Postman Workspace

on:
  push:
    branches: [ develop ]

jobs:
  update-postman-collection:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Sync Postman Collections
      uses: jneate/postman-collection-action@v1
      with:
        postmanApiKey: ${{ secrets.POSTMAN_API_KEY }}
        postmanWorkspaceId: ${{ vars.POSTMAN_WORKSPACE_ID }}
